import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const merienda = localFont({
  src: "./fonts/Merienda.woff",
  variable: "--font-merienda",
  weight: "300 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${merienda.variable}  antialiased flex flex-col min-h-screen max-w-[1920px] mx-auto `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
